version: "3"

services:
  mysql-backup:
    image: philippdormann/mariadb-backup-s3
    environment:
      - FILE_PREFIX=
      - S3_BUCKET=
      - S3_ACCESS=
      - S3_SECRET=
      - S3_SERVER=
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PORT=
      - WAIT_SECONDS=86400
      - INITIAL_BACKUP=yes
