
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-mysql-backup
spec:
  schedule: "5 */8 * * *"
  concurrencyPolicy: Replace
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: mysql-backup-my-app
            image: philippdormann/mariadb-backup-s3
            env:
              - name: S3_ACCESS
                value: xxxxxx
              - name: S3_SECRET
                value: yyyyyyyyyyyyyyyyyy
              - name: S3_SERVER
                value: s3.endpoint.com
              - name: S3_NAME
                value: folder-name/backup-name
              - name: S3_BUCKET
                value: backup-s3-bucket-name
              - name: DB_USER
                value: user
              - name: DB_PASSWORD
                value: password
              - name: DB_HOST
                value: host-or-service-name
              - name: DB_PORT
                value: port
---
