name: Docker Image CI
on:
  push:
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: vars
      run: |
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
        echo "::set-output name=current_tag::$(git describe --tags --abbrev=0)"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag philippdormann/mariadb-backup-s3:${{steps.vars.outputs.sha_short}} --tag philippdormann/mariadb-backup-s3:${{steps.vars.outputs.current_tag}} --tag philippdormann/mariadb-backup-s3
    - name: Login to Dockerhub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the Docker image
      run:  docker push philippdormann/mariadb-backup-s3:${{steps.vars.outputs.sha_short}}
    - name: Push the Docker image
      run:  docker push philippdormann/mariadb-backup-s3:${{steps.vars.outputs.current_tag}}
    - name: Push the :latest Docker image
      run:  docker push philippdormann/mariadb-backup-s3
